algoritmo "aula0"
// Função : Soma de A e B
// Autor : Raphael Medeiros
// Data : 11/05/2022
// Seção de Declarações 

var A, B ,resultado: real

inicio
// Seção de Comandos
escreva("Informe um valor real para A: ")
leia(A)

escreva("Informe um valor real para B: ")
leia(B)
resultado <- (A+B)

//Pular linha apenas por estética
escreval("")

escreval("A soma de A e B eh:", resultado)

fimalgoritmo
